--- 
jobs: 
  publish_to_expo_dev: 
    docker: 
      - 
        image: "circleci/node:10.13.0"
    environment: 
      EXPO_RELEASE_CHANNEL: dev
    steps: 
      - checkout
      - 
        run: 
          command: "npm install"
          name: "Installing dependencies"
      - 
        run: 
          command: "yarn run test --forceExit"
          name: "Jest Tests"
      - 
        run: 
          command: "npx expo-cli login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD"
          name: "Login into Expo"
      - 
        run: 
          command: "npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL"
          name: "Publish to Expo"
    working_directory: ~/eresamont2
  publish_to_expo_prod: 
    docker: 
      - 
        image: "circleci/node:10.13.0"
    environment: 
      EXPO_RELEASE_CHANNEL: default
    steps: 
      - checkout
      - 
        run: 
          command: "npm install"
          name: "Installing dependencies"
      - 
        run: 
          command: "yarn run test --forceExit"
          name: "Jest Tests"
      - 
        run: 
          command: "npx expo-cli login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD"
          name: "Login into Expo"
      - 
        run: 
          command: "npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL"
          name: "Publish to Expo"
    working_directory: ~/eresamont2
publish: 
  docker: 
    - 
      image: "circleci/node:10.13.0"
  steps: 
    - checkout
    - 
      run: 
        command: "npm install"
        name: "Installing dependencies"
    - 
      run: 
        command: "yarn run test --forceExit"
        name: "Jest Tests"
    - 
      run: 
        command: "npx expo-cli login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD"
        name: "Login into Expo"
    - 
      run: 
        command: "npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL"
        name: "Publish to Expo"
  working_directory: ~/eresamont2
version: 2
workflows: 
  my_app: 
    jobs: 
      - 
        publish_to_expo_dev: 
          context: expo_login
          filters: 
            branches: 
              only: master
      - 
        publish_to_expo_prod: 
          context: expo_login
          filters: 
            branches: 
              only: master
  nightly-workflow: 
    jobs: 
      - 
        publish_to_expo_prod: 
          context: expo_login
          filters: 
            branches: 
              only: master
    triggers: 
      - 
        schedule: 
          cron: "0 0 * * *"
          filters: 
            branches: 
              only: 
                - master
  version: 2
