---
version: 2
publish: &publish
  working_directory: ~/eresamont2
  docker:
    - image: circleci/node:10.13.0
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm install

    - run:
        name: Jest Tests
        command: yarn run test --forceExit

    - run:
        name: Login into Expo
        command: npx expo-cli login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          context: expo_login
          filters:
            branches:
              only: master
      - publish_to_expo_prod:
          context: expo_login
          filters:
            branches:
              only: master
